imports:
    - { resource: services/handler_factory.yaml }
    - { resource: services/logger_factory.yaml }

parameters:
    app.docs_uri: '%env(DOCS_URI)%'

services:
    Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    CSL\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
